USE [master]
GO

/****** Object:  Database [TopPuzzle]    Script Date: 16.12.2014 0:18:17 ******/
CREATE DATABASE [TopPuzzle]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'TopPuzzle', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\TopPuzzle.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'TopPuzzle_log', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\TopPuzzle_log.ldf' , SIZE = 2048KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [TopPuzzle] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [TopPuzzle].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [TopPuzzle] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [TopPuzzle] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [TopPuzzle] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [TopPuzzle] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [TopPuzzle] SET ARITHABORT OFF 
GO

ALTER DATABASE [TopPuzzle] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [TopPuzzle] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [TopPuzzle] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [TopPuzzle] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [TopPuzzle] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [TopPuzzle] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [TopPuzzle] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [TopPuzzle] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [TopPuzzle] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [TopPuzzle] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [TopPuzzle] SET  DISABLE_BROKER 
GO

ALTER DATABASE [TopPuzzle] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [TopPuzzle] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [TopPuzzle] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [TopPuzzle] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [TopPuzzle] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [TopPuzzle] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [TopPuzzle] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [TopPuzzle] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [TopPuzzle] SET  MULTI_USER 
GO

ALTER DATABASE [TopPuzzle] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [TopPuzzle] SET DB_CHAINING OFF 
GO

ALTER DATABASE [TopPuzzle] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [TopPuzzle] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [TopPuzzle] SET  READ_WRITE 
GO


USE [TopPuzzle]
GO

/****** Object:  Table [dbo].[Users]    Script Date: 16.12.2014 0:41:00 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Users](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Login] [nvarchar](50) NOT NULL,
	[Password] [nvarchar](50) NOT NULL,
	[Email] [nvarchar](50) NULL
) ON [PRIMARY]

GO

/****** Object:  Table [dbo].[Top]    Script Date: 16.12.2014 0:18:52 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Top](
	[Time] [int] NOT NULL,
	[UserId] [int] NOT NULL,
	[Date] [nvarchar](50) NOT NULL
) ON [PRIMARY]

GO


